---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint -x 106
platforms:
  - name: test-nextcloud-centos
    image: centos:8
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    published_ports:
      - 0.0.0.0:8000:80
      - 0.0.0.0:4430:443
provisioner:
  name: ansible

verifier:
  name: testinfra
